import './Academy.css';

function Academy({ language }) {
    return (
        <div className='academy-section'>
            <div className='academy-section-box'>
                {language === 'tr' ? (
                    <>
                        <h1 className='academy-title'>Web Tasarım Nedir?</h1>
                        <p><span className='academy-p-span'>"Web tasarım nedir?"</span> veya <span className='academy-p-span'>"Web tasarımı nedir?"</span> sorusuna akademik olarak verilebilecek en kısa cevap şu şekildedir;</p>
                        <p>Web tasarım, son kullanıcıların hedeflenen içeriğe kolayca ulaşması amacıyla yapılan web sayfalarının, yazılımını, tasarımını ve güncellenmesini ifade eder. Genellikle yazılım geliştirmeden ziyade web sitesi geliştirmenin kullanıcı deneyimi yönlerini kapsar. Web tasarımda grafik tasarım ve ara yüz tasarımı gibi birçok temel alan vardır. Web tasarımı eskiden masaüstü tarayıcılar için web siteleri tasarlamaya odaklanırdı; ancak, 2010'ların ortalarından bu yana, mobil telefon ve tablet cihazları ile uyumlu (Responsive) olan web tasarım giderek daha önemli hale geldi. Günümüzde Web tasarım, şahıs veya firmalar tarafından satışa sunulan ürün ve hizmetleri, kişisel bilgileri veya hedeflenen içeriği internet ortamında tanıtmak üzere yapılmaktadır. Belirli bir hedef ve prensipler ile oluşturulan web tasarımın uygulamaya geçirilmesi, web sitesini meydana getirir. Bir başka deyişle; gerçek veya tüzel kişileri ve bu kişilerin sunduğu hizmet ve ürünleri sanal ortamda temsil etmesi için web sitesi tasarlama işine ve bu kapsamda yapılan çalışmalar bütününe 'web tasarım' denir.</p>
                        <p>İyi bir web tasarımın kullanımı kolaydır, estetik açıdan hoştur ve web sitesinin kullanıcı grubuna ve markasına uygundur. Çoğu web sayfası basitliğe odaklanılarak tasarlanmıştır, böylece kullanıcıların dikkatini dağıtabilecek veya kafasını karıştırabilecek gereksiz bilgi ve işlevler içermez. Bir web sitenin temel prensibi hedef kitlenin güvenini kazanan ve teşvik eden bir site olduğundan, mümkün olduğunca çok sayıda potansiyel kullanıcı için hayal kırıklığı noktasını ortadan kaldırmak kritik bir husustur.</p>
                        <p>Hem masaüstü hem de mobil cihazlarda iyi çalışan web siteleri tasarlamak için en yaygın yöntemlerden ikisi, duyarlı ve uyarlanabilir tasarımdır. Duyarlı tasarımda (Responsive) içerik, ekran boyutuna bağlı olarak dinamik olarak hareket eder; uyarlanabilir tasarımda ise, web sitesi içeriği, ortak ekran boyutlarıyla eşleşen düzen boyutlarında sabitlenir. Cihazlar arasında mümkün olduğunca tutarlı bir düzeni korumak, kullanıcı güvenini ve katılımını sürdürmek için çok önemlidir.</p>
                        <h1 className='academy-title'>Web Tasarım Nasıl Yapılır?</h1>
                        <p>Günümüzde Dünya üzerinde 1.5 milyardan fazla web sitesi bulunmaktadır. Her gün, saat, dakika ve hatta saniye, sayıları giderek artmaktadır. Bazı siteler aktif değilken, büyük bir çoğunluğu her gün kullanılıyor ve insanlar neredeyse onlarsız yaşayamıyorlar. Halihazırda pek çok web sitesi olmasına ve aralarındaki rekabet büyük olmasına rağmen, insanlar yine de kendilerine ait bir şeyler yaratmak ve dünyaya yeni fikirler sunmak istiyor. Ve asıl soru, insanların her gün kullanmaktan hoşlanmaları için web tasarım veya bir başka deyişle web sitesi tasarımı nasıl yapılır?</p>
                        <h2 className='academy-title-h2'><span class='academy-title-h2-step'>1. Adım:</span> Web Tasarım Planlaması</h2>
                        <p>İyi bir web sitesi tasarımı nasıl yapılır? Her şey ilk aşama olan web tasarım planıyla başlar. Web tasarımı oluşturmaya bir plan olmadan başlarsanız, bu durum zaman ve para kaybına neden olabilir.</p>
                        <p>Web Tasarım Sistemleri genellikle aşağıdaki öğelerden oluşan bir web sitesi tasarım planını takip eder:</p>
                        <ul>
                            <li>•Tasarım aşamasına geçmeden önce gereksinimlerini anlamak için müşterilerimizle projeyi tartışırız;</li>
                            <li>•Web sitesinin hangi markayı tanıtması gerektiğini keşfederiz.</li>
                            <li>•Yaklaşık bir tasarım belirlemek için oluşturulacak web sitesinin içermesi gereken özellikleri inceleriz.</li>
                            <li>•Kullanıcıların tam olarak istediklerini sağlamak için oluşturulacak web sitesinin hedef kitlesini belirleriz.</li>
                        </ul>
                        <p>Bu ipuçları, güzel görünen bir UI / UX web sitesi tasarımı oluşturmamıza ve istenmeyen hataları ve revizyonları önlememize yardımcı olacaktır.</p>
                        <h2 className='academy-title-h2'><span class='academy-title-h2-step'>2. Adım:</span> Rakip Araştırması</h2>
                        <p>Sitenin konusuna, türüne ve amacına karar verdiğinizde ve yaklaşık bir plan yaptığınızda, ilk iş rakipleri dikkatlice inceleme olmalıdır. Rakip web sitelerini araştırırken, bilgilerin nerede ve nasıl bulunduğuna, hangi site yapısının ve işlevselliğinin uygulandığına dikkat edin. Birkaç düzine siteyi analiz ettikten sonra, muhtemelen hedeflenen alandaki sitelere özgü standart özellikleri ve kalıpları göreceksiniz.
                            Sitenin görsel bileşeni, tasarımcının en önemli görevlerinden biridir çünkü kullanışlı ve güzel olmalıdır. Yazı tiplerini, ana gölgeleri seçmeniz, blokların tasarımını, sayfadaki bilgilerin düzenini düşünmeniz gerekir.
                            Tasarımda yeniyseniz, bunu kendi başınıza yapmak şüpheli bir karardır. Beğendiğiniz sitelerin örneklerini bulmak ve bazı fikirleri benimsemek en iyisidir. Sadece, beğendiğiniz siteyi tamamen kopyalamayın bu açık bir intihaldir. Tasarımını beğendiğiniz ilgili konudan birkaç düzine (veya daha fazla) siteden seçim yapmanızı öneririz. Rekabetçi olmak için bir şekilde öne çıkmanız gerekir, bu nedenle işleri hakkında çok şey bilen profesyonellere yönelmek daha iyidir bu sayede bir web sitesi tasarımı oluştururken herhangi bir sorun yaşamazsınız.</p>
                        <h2 className='academy-title-h2'><span class='academy-title-h2-step'>3. Adım:</span> UX(Kullanıcı Deneyimi) Tasarımı</h2>
                        <p>Web sitenizin konseptine karar verdikten sonra, doğrudan tasarımın oluşturulmasına başlayabilirsiniz.
                            Bu aşamada site tasarımının ne olması gerektiğine dair bir anlayış geliştirmelisiniz. Nasıl yapılacağını düşünmeye oldukça fazla zaman ayırmalısınız. İlk olarak, web sitesinin "iskeletini" wireframe'i oluşturmamız gerekiyor. Framework’ler, sitenin görsel tasarımı ve içerik öğelerinin tutulması için bir çerçeve sağlar ve site haritası ile ilgili olası zorlukları ve boşlukları ortaya çıkarmaya yardımcı olur. Bir framework herhangi bir nihai tasarım öğesi olmasa da, sonunda sitenin nasıl görüneceği konusunda bir rehber görevi görür. Ayrıca çeşitli öğelerin biçimlendirilmesi için ilham kaynağı olabilir. UX, web sitesi kullanılabilirliği elde tutma oranı için önemli olduğundan dolayı, bir tasarım oluşturmanın ayrılmaz bir parçasıdır.
                            Önceden, framework’ler oluşturmak için yalnızca Photoshop kullanılıyordu, ancak modern tasarımcılar çok daha fazla web sitesi tasarım aracına sahiptir. Artık sizin için de tam olarak istediğiniz şekilde kolayca framework’ler oluşturacak çok sayıda yardımcı var. Biz framework web tasarım uygulamaları arasında Sketch ve Figma'yı öneriyoruz.
                            Bir site oluşturmak için bir program seçtiğinizde, hedeflerinizi yeniden düşünün. İşletmenizi tanıtacak küçük bir siteye ihtiyacınız varsa, bunu kendiniz oluşturabilirsiniz. Basit bir web sitesi, kendi başınıza oluşturmak istiyorsanız ilk başta çok yararlı olabilir, ancak size marka bilinirliği veya yüksek olası satış dönüşümü sağlamaz. Daha yüksek bir seviyeye ulaşmayı ve bazı ticari hedeflere ulaşmayı planlıyorsanız, bu alanda kapsamlı deneyime sahip ve iyi görünümlü, modern, kaliteli, temiz ve duyarlı bir web sitesi oluşturmak için tam olarak ne gerektiğini bilen uzmanlara ve profesyonellere başvurmak daha iyidir.</p>
                        <h2 className='academy-title-h2'><span class='academy-title-h2-step'>4. Adım:</span> Web Sitesi İçeriği Oluşturma</h2>
                        <p>Web tasarım sürecine devam ederken, en önemli web sitesi tasarım öğelerinden biri olan yazılı içerikler de oluşturmalısınız.
                            İlk olarak içeriğin, okuyucuların veya ziyaretçilerin dikkatini çekmesi gerekmektedir. Çok uzun, sıkıcı ve cansız metinler nadiren okuyucuların dikkatini çeker. Hızlı, ilgi çekici ve heyecan verici içerik oluşturmak önemlidir, bu da sizin diğer rakiplerinizi geçmenizi sağlar.
                            Bu nedenle, içerik oluşturma üzerinde uzun süre çalışmanız gerekir. Kendi başınıza içerik yazma konusunda şüpheniz varsa, içerik oluşturma konusunda deneyime sahip profesyonel yazarlarla iletişime geçmek en iyisidir.
                            Bu noktada SEO'ya (Arama Motoru Optimizasyonu) da dikkat etmeniz gerekiyor. SEO uyumlu içerik yazmanız, sitenizin Google aramalarında üst sıralara çıkmasına yardımcı olur. Potansiyel müşterilerin ilgisini çekmek için metin yazmak, bir SEO yazarı gerektirir. SEO'nun 2024'te hala önemli olduğunu unutmayın, bu nedenle işinizin farklı yönleri hakkında yazmak için birkaç saat harcamaktan çekinmeyin. Web sitesi geliştirme sürecinde, içerik yazmak işin büyük bir bölümünü oluşturur, bu nedenle uzun süre çalışmanız gerekir. SEO'nun 2024'te hala önemli olduğunu unutmayın, bu nedenle işinizin farklı yönleri hakkında yazmak için birkaç saat harcamaktan çekinmeyin. Web sitesi geliştirme sürecinde, içerik yazmak işin büyük bir bölümünü oluşturur, bu nedenle uzun süre çalışmanız gerekir.</p>
                        <h2 className='academy-title-h2'><span class='academy-title-h2-step'>5. Adım:</span> Web Sitesi Prototipi</h2>
                        <p>Prototipleme, nihai web sitesi oluşturulmadan önce bir sitenin genel yapısının ve işlevselliğinin oluşturulması sürecidir. Bu aşamada, tasarımcılar, geliştiriciler ve diğer paydaşlar, sitenin nasıl çalışacağını ve nasıl görüneceğini gözden geçirir ve üzerinde çalışırlar. Prototipler, bir sitenin kullanıcı deneyimini ve etkileşimlerini test etmek için kullanılır, bu da nihai tasarımın kullanıcı dostu ve etkili olmasını sağlar.
                            Prototip oluşturma, genellikle bir site haritası ve wireframe'ler oluşturmayı içerir. Site haritası, sitenin farklı sayfalarının ve bölümlerinin nasıl organize edileceğini gösterir, wireframe'ler ise her sayfanın düzenini ve yapısını gösterir. Bu aşama, tasarımın ve içeriğin nihai siteye nasıl entegre edileceğini anlamak için kritik bir adımdır.</p>
                        <h2 className='academy-title-h2'><span class='academy-title-h2-step'>6. Adım:</span> Web Sitesi Testi ve Yayına Alma</h2>
                        <p>Web sitesi tamamlandıktan sonra, yayına alınmadan önce kapsamlı bir test sürecinden geçmelidir. Bu, sitenin farklı tarayıcılarda ve cihazlarda düzgün çalıştığını, tüm bağlantıların ve formların işlevsel olduğunu ve içeriğin hatasız olduğunu doğrulamak için gereklidir.
                            Test aşamasında, kullanıcı deneyimini de göz önünde bulundurmalısınız. Kullanıcıların siteyi nasıl kullanacaklarını ve etkileşimde bulunacaklarını gözlemleyerek, tasarımda veya işlevsellikte yapılması gereken değişiklikleri belirleyebilirsiniz. Bu, sitenin kullanıcı dostu ve etkili olmasını sağlamanın önemli bir adımıdır.
                            Web sitesi testi tamamlandıktan ve gerekli düzeltmeler yapıldıktan sonra, site yayına alınabilir. Bu aşamada, sitenin sunucuya yüklenmesi ve alan adıyla ilişkilendirilmesi gereklidir. Site yayına alındıktan sonra, düzenli bakım ve güncellemelerle sitenin performansını ve güvenliğini sağlamalısınız.</p>
                        <h2 class='academy-title-h2'><span class='academy-title-h2-step'>7. Adım:</span> Web Sitesini Yayınlamak</h2>
                        <p>Web sitesi tasarım süreci adımlarını tamamlamak, web sitesi tasarım sürecinde herkesin en sevdiği bölümdür. Her şey kapsamlı bir şekilde test edildiğinde ve siteden memnun olduğunuzda, web sitesini yayınlayın.
                            Her şeyin bir anda mükemmel olacağını düşünmeyin. İnce ayar yapılması gereken öğeler illaki olabilir. Esas olan, web tasarımında işlevsellik ve form arasındaki doğru dengeyi bulmaktır.
                            Yalnızca doğru yazı tipini ve renkleri kullanmakla kalmamalı, aynı zamanda kullanıcılarınızın sitede gezinmesinin ne kadar rahat ve kolay olduğunu da anlamalısınız.
                            Yayınlama aşamasın tamamlanması, sitenizin kusursuz olduğunu düşündüğünüz ana kadar sizi zorlayabilir. Siteniz çalışmaya başladığında, sürekli olarak içerik testini başlatabilir, analizleri izleyebilir ve herhangi bir kusur varsa iyileştirebilirsiniz.</p>
                        <h2 className='academy-title-h2'>Özet</h2>
                        <p>Yukarıda bahsedilenlerin hepsini özetlemek gerekirse, web tasarım sürecinin gerçekten o kadar da basit olmadığını söylemek gerekir. Sitenin planlanması, içeriği ve görsel tasarımı gerçekten çok çaba ve fikir gerektirir, ancak gerçekten iyi bir sonuç elde etmek ve işletmenizi çok iyi tanıtmak istiyorsanız, o zaman tam olarak ihtiyacınız olan şey profesyonel bir web sitesidir.</p>
                    </>
                ) : (
                    <>
                        <h1 className='academy-title'>What is Web Design?</h1>
                        <p>The shortest academic answer to the question "What is web design?" or "What is web designing?" is as follows:</p>
                        <p>Web design refers to the creation, design, and maintenance of web pages to ensure end-users can easily access the intended content. It usually focuses on the user experience aspects of website development rather than software development. Web design encompasses many core areas such as graphic design and interface design. Initially, web design focused on creating websites for desktop browsers; however, since the mid-2010s, designing web pages compatible with mobile phones and tablet devices (Responsive) has become increasingly important. Nowadays, web design is used by individuals or companies to promote their products and services, personal information, or targeted content on the internet. Implementing a web design created with specific goals and principles results in the creation of a website. In other words, the work of designing a website to represent individuals or organizations and the services and products they offer in the virtual environment is called 'web design'.</p>
                        <p>A good web design is easy to use, aesthetically pleasing, and suits the user group and brand of the website. Most web pages are designed with a focus on simplicity, avoiding unnecessary information and functions that might distract or confuse users. Since the main principle of a website is to build and encourage the trust of its target audience, eliminating as many potential points of frustration as possible for users is critical.</p>
                        <p>Two of the most common methods for designing websites that work well on both desktop and mobile devices are responsive and adaptive design. In responsive design, content moves dynamically depending on the screen size; in adaptive design, website content is fixed in layout sizes that match common screen sizes. Maintaining a consistent layout across devices is essential for maintaining user trust and engagement.</p>
                        <h1 className='academy-title'>How to Create Web Design?</h1>
                        <p>There are over 1.5 billion websites worldwide today. Their numbers are increasing every day, hour, minute, and even second. While some sites are inactive, a vast majority are used daily, and people can hardly live without them. Despite the many existing websites and fierce competition among them, people still want to create something of their own and present new ideas to the world. And the main question is, how to create web design or, in other words, a website design that people will enjoy using daily?</p>
                        <h2 className='academy-title-h2'><span className='academy-title-h2-step'>Step 1:</span> Web Design Planning</h2>
                        <p>How to create a good website design? Everything starts with the first phase, the web design plan. Starting to create web design without a plan can lead to a waste of time and money.</p>
                        <p>Web Design Systems typically follow a web design plan consisting of the following elements:</p>
                        <ul>
                            <li>•We discuss the project with our clients to understand their requirements before moving on to the design phase;</li>
                            <li>•We discover which brand the website needs to promote.</li>
                            <li>•We review the features the website should include to determine an approximate design.</li>
                            <li>•We identify the target audience of the website to provide exactly what users want.</li>
                        </ul>
                        <p>These tips help us create a beautiful UI/UX website design and avoid unwanted errors and revisions.</p>
                        <h2 className='academy-title-h2'><span class='academy-title-h2-step'>Step 2:</span> Competitor Research</h2>
                        <p>Once you decide on the site's subject, type, and purpose and have an approximate plan, the first task should be to carefully examine the competitors. When researching competitor websites, pay attention to where and how information is found, and what site structure and functionality are applied. After analyzing several dozen sites, you will likely see standard features and patterns specific to the targeted area.
                            The visual component of the site is one of the most important tasks of the designer because it should be useful and beautiful. You need to choose fonts, main shadows, consider the design of blocks, and the layout of information on the page.
                            If you are new to design, doing it yourself is a doubtful decision. It's best to find examples of sites you like and adopt some ideas. Just don't completely copy the site you like, as this is outright plagiarism. We recommend choosing a few dozen (or more) sites related to the topic you like. To be competitive, you need to stand out somehow, so it's better to turn to professionals who know a lot about their business, ensuring you don't encounter any problems when creating a web design.</p>
                        <h2 className='academy-title-h2'><span class='academy-title-h2-step'>Step 3:</span> UX (User Experience) Design</h2>
                        <p>Once you decide on the concept of your website, you can start directly creating the design.
                            At this stage, you should develop an understanding of what the site design should be. You need to spend quite a lot of time thinking about how to do it. First, we need to create the "skeleton" of the website, the wireframe. Frameworks provide a framework for holding the visual design and content elements of the site and help identify potential difficulties and gaps related to the site map. Although a framework is not any final design element, it serves as a guide for how the site will eventually look. It can also inspire the formatting of various elements. UX is an integral part of creating a design, as it is crucial for the usability and retention rate of a website.
                            Previously, only Photoshop was used to create frameworks, but modern designers have many more web design tools. Now there are many helpers that will easily create frameworks exactly as you want. We recommend Sketch and Figma among framework web design applications.
                            When choosing a program to create a site, reconsider your goals. If you need a small site to promote your business, you can create it yourself. A simple website can be very useful if you want to create it yourself initially, but it will not provide you with brand awareness or high lead conversion. If you plan to reach a higher level and achieve some commercial goals, it is better to turn to experts and professionals who have extensive experience in this field and know exactly what it takes to create a successful website. If you want to do something professional, turn to professionals, as this will save your time and prevent you from making mistakes.</p>
                        <h2 className='academy-title-h2'><span class='academy-title-h2-step'>Step 4:</span> UI (User Interface) Design</h2>
                        <p>UI (user interface) design is also an important component. The more attractive and convenient your site is, the higher the chance it will interest your users. We need to create user-friendly interfaces for the website. If you are new to design and don't have experience in this field, contacting professionals is the best solution. Experienced web designers will create the appropriate interface design for your site, allowing you to engage more users.
                            Therefore, you need to spend a lot of time creating content. If you have doubts about writing content yourself, it is best to contact professional writers with experience in content creation.
                            At this point, you also need to pay attention to SEO (Search Engine Optimization). Writing SEO-friendly content will help your site rank higher in Google searches. Writing copy to attract potential customers requires an SEO writer. Remember that SEO is still important in 2024, so don't hesitate to spend a few hours writing about different aspects of your business. Creating content is a big part of the website development process, so you need to work long hours.</p>
                        <h2 className='academy-title-h2'><span class='academy-title-h2-step'>Step 5:</span> Website Prototype</h2>
                        <p>Prototyping is the process of creating the overall structure and functionality of a site before the final website is created. At this stage, designers, developers, and other stakeholders review and work on how the site will work and look. Prototypes are used to test a site's user experience and interactions, ensuring that the final design is user-friendly and effective.
                            Creating a prototype typically involves creating a site map and wireframes. The site map shows how the different pages and sections of the site will be organized, while wireframes show the layout and structure of each page. This stage is crucial for understanding how the design and content will integrate into the final site.</p>
                        <h2 className='academy-title-h2'><span class='academy-title-h2-step'>Step 6:</span> Website Testing and Launch</h2>
                        <p>Once the website is complete, it should go through a thorough testing process before going live. This is necessary to ensure that the site works properly on different browsers and devices, all links and forms are functional, and the content is error-free.
                            During the testing phase, you should also consider the user experience. By observing how users use and interact with the site, you can identify any necessary changes in design or functionality. This is an important step in ensuring that the site is user-friendly and effective.
                            Once website testing is complete and any necessary corrections are made, the site can go live. At this stage, the site needs to be uploaded to the server and associated with the domain name. After the site goes live, you should regularly maintain and update it to ensure its performance and security.</p>
                        <h2 className='academy-title-h2'><span class='academy-title-h2-step'>Step 7:</span> Publishing the Website</h2>
                        <p>Completing the web design process steps can be the favorite part of everyone involved in the web design process. When everything has been thoroughly tested and you are satisfied with the site, publish the website.</p>
                        <h2 className='academy-title-h2'>Summary</h2>
                        <p>To summarize all of the above, it must be said that the web design process is really not that simple. Planning, content and visual design of the site really require a lot of effort and ideas, but if you really want to achieve a good result and promote your business very well, then a professional website is exactly what you need.</p>
                    </>
                )}
            </div>
        </div>
    );
}

export default Academy;
